# Generated by Django 6.0.2 on 2026-02-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table='optimizer',
        ),
    ]
